api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

get_product_details:
    path: /GetProductDetails
    defaults: { _controller: ApiBundle:GetProductDetails:get }

get_product_filters:
    path: /GetProductFilters
    defaults: { _controller: ApiBundle:GetProductFilters:get }

search_products:
    path: /SearchProducts
    defaults: { _controller: ApiBundle:SearchProducts:get }

get_author_details:
    path: /GetAuthorDetails
    defaults: { _controller: ApiBundle:GetAuthorDetails:get }

get_recipe_details:
    path: /GetRecipeDetails
    defaults: { _controller: ApiBundle:GetRecipeDetails:get }

get_recipe_filters:
    path: /GetRecipeFilters
    defaults: { _controller: ApiBundle:GetRecipeFilters:get }

search_recipes:
    path: /SearchRecipes
    defaults: { _controller: ApiBundle:SearchRecipes:get }

test:
    path: /test
    defaults: { _controller: ApiBundle:Test:test }